project: 
  type: website
  
website: 
  page-navigation: true
  title: "LJMU Bag of tRicks Worshop Series" 
  site-url: "https://LJMUtRicks.github.io" 
  repo-url: https://github.com/LJMUtRicks/bag-of-tricks
  repo-actions: [edit, source, issue]
  favicon: images/Slide1  
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
  
  sidebar:
    background: "#D9E3E4"
    logo: "images/Slide2.png"
    favicon: images/Slide3.png
    pinned: true
    align: center
    tools: 
      - icon: Slide3.png
        href: https://www.ljmu.ac.uk/about-us/faculties/faculty-of-science/school-of-biological-and-environmental-sciences
        text: "School of BES, LJMU"
      - icon: github
        href: https://github.com/LJMUtRicks
        text: "LJMU Bag of tRicks"
      

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about-bag.qmd
        text: About Bag of tRicks
      - href: about-BES.qmd
        text: About LJMU
      - section: Sessions
        text: Community Sessions
        contents: 
          - href: Sessions/Overview.qmd
            text: Current Overview  
          - href: Sessions/One.qmd
            text: First session
          - href: Sessions/Two.qmd
            text: Second session          
      - contact.qmd
    #  - resources.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
