project: 
  type: website
  
website: 
  page-navigation: true
  title: "LJMU Bag of tRicks Worshop Series" 
  site-url: "https://LJMUtRicks.github.io" 
  repo-url: https://github.com/LJMUtRicks/bag-of-tRicks
  repo-actions: [edit, source, issue]
  favicon: images/Slide1  
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2024"
  
  sidebar:
    background: "#D9E3E4"
    logo: "images/logo-transparent-crop.png"
    favicon: images/Slide3.png
    pinned: true
    align: center
    tools: 
      - icon: Slide3.png
        href: https://www.ljmu.ac.uk/about-us/faculties/faculty-of-science/school-of-biological-and-environmental-sciences
        text: "School of BES, LJMU"
      - icon: github
        href: https://github.com/LJMUtRicks
        text: "LJMU Bag of tRicks"
      

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: about-openscapes.qmd
        text: About Openscapes
      - href: about-nmfs-openscapes.qmd
        text: About NMFS Openscapes
      - section: mentors/index.qmd
        text: Mentors Community
        contents: 
          - href: mentors/activities.qmd
            text: Current Activities  
          - href: mentors/activities.html#previous-activities
            text: Previous activities
          - href: mentors/mentor-calls.qmd
            text: Mentor Calls Skills            
      - href: champions.qmd
        text: Champions Program      
      - section: cohorts/index.qmd
        text: Champions Cohorts
        contents: 
          - cohorts/NMFS-fall2024.qmd  
          - cohorts/NMFS-fall2022.md 
          - cohorts/SEFSC-sum2022.md 
          - cohorts/AFSC-win2021.md 
          - cohorts/FDD-fall2021.md
          - cohorts/NMFS-fall2021.md
          - cohorts/NEFSC-spr2020.md            
      - href: data-academy.qmd
        text: Data Academy
      - href: media.qmd
        text: Presentations and Media
      - href: blog.qmd
        text: Blog
      - contact.qmd
      - resources.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
